import { jsPDF } from 'jspdf';

/**
 * Downloads plain text / markdown content as a file
 */
export const exportToMarkdown = (filename: string, content: string) => {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename.endsWith('.md') ? filename : `${filename}.md`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Downloads HTML formatted content as a Word DOC file
 */
export const exportToDOCX = (filename: string, title: string, markdownContent: string) => {
  // Convert basic markdown tags to HTML elements for Word
  const htmlBody = markdownContent
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    .replace(/^\* (.*$)/gim, '<ul><li>$1</li></ul>')
    .replace(/^- (.*$)/gim, '<ul><li>$1</li></ul>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/\n/g, '<br/>');

  const contentHtml = `
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #333333; padding: 20px; }
        h1 { color: #a855f7; font-size: 24px; border-bottom: 2px solid #a855f7; padding-bottom: 5px; }
        h2 { color: #22d3ee; font-size: 18px; margin-top: 20px; }
        h3 { font-size: 16px; margin-top: 15px; }
        ul { margin-bottom: 10px; }
        li { margin-bottom: 5px; }
        strong { color: #111111; }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <p style="font-size: 11px; color: #666666;">Generated by SmartDocs AI Platform on ${new Date().toLocaleDateString()}</p>
      <hr/>
      ${htmlBody}
    </body>
    </html>
  `;

  const blob = new Blob(['\ufeff' + contentHtml], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename.endsWith('.docx') ? filename : `${filename}.docx`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Downloads content as a PDF file
 */
export const exportToPDF = (filename: string, title: string, markdownContent: string) => {
  const doc = new jsPDF();
  
  // Title
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(168, 85, 247); // purple
  doc.text(title, 20, 20);
  
  // Date
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated by SmartDocs AI on ${new Date().toLocaleDateString()}`, 20, 27);
  
  // Horizontal line
  doc.setDrawColor(220, 220, 220);
  doc.line(20, 30, 190, 30);
  
  // Body text formatting
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);
  
  // Clean markdown syntax for standard text PDF rendering
  const cleanText = markdownContent
    .replace(/^#+ /gm, '')
    .replace(/\*\*/g, '')
    .replace(/\*/g, '')
    .replace(/^- /gm, '• ')
    .replace(/^\* /gm, '• ');

  const splitText = doc.splitTextToSize(cleanText, 170);
  
  let y = 38;
  const pageHeight = doc.internal.pageSize.height;
  
  splitText.forEach((line: string) => {
    if (y > pageHeight - 20) {
      doc.addPage();
      y = 20; // reset y on new page
    }
    doc.text(line, 20, y);
    y += 7;
  });
  
  doc.save(filename.endsWith('.pdf') ? filename : `${filename}.pdf`);
};
